# PVE Manager V2.0 启动脚本 (Windows PowerShell)
# PVE Manager V2.0 Start Script (Windows PowerShell)
#
# 新功能包括:
# - 多用户权限管理
# - 批量操作（启动/关机/重启）
# - 虚拟机分组管理
# - 备份管理
# - VNC远程控制
# - 操作日志审计
# - 定时任务调度
# - 系统设置
#
# 默认管理员账户: admin / admin123

param(
    [switch]$Init,
    [switch]$Reset,
    [switch]$ResetDB,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

# 颜色输出函数
function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$ForegroundColor = "White"
    )
    Write-Host $Message -ForegroundColor $ForegroundColor
}

function Print-Info { Write-ColorOutput "[INFO] $args" "Cyan" }
function Print-Success { Write-ColorOutput "[SUCCESS] $args" "Green" }
function Print-Warning { Write-ColorOutput "[WARNING] $args" "Yellow" }
function Print-Error { Write-ColorOutput "[ERROR] $args" "Red" }

function Print-Header {
    param([string]$Title)
    Write-ColorOutput "========================================" "Magenta"
    Write-ColorOutput "    $Title" "Magenta"
    Write-ColorOutput "========================================" "Magenta"
}

# 获取本机IP地址
function Get-LocalIP {
    try {
        $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { 
            $_.InterfaceAlias -notlike "*Loopback*" -and 
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*"
        } | Select-Object -First 1).IPAddress
        return $ip
    } catch {
        return $null
    }
}

# 验证端口号
function Validate-Port {
    param([int]$Port)
    return ($Port -ge 1000 -and $Port -le 65535)
}

# 加载环境变量
function Load-Env {
    if (Test-Path ".env.global") {
        Print-Info "加载全局配置文件: .env.global"
        Get-Content ".env.global" | ForEach-Object {
            if ($_ -match "^([^#=]+)=(.*)$") {
                $name = $matches[1].Trim()
                $value = $matches[2].Trim()
                Set-Item -Path "env:$name" -Value $value
            }
        }
        return $true
    }
    return $false
}

# 保存环境变量
function Save-Env {
    $content = @"
# PVE Manager 全局配置文件
# Global configuration file for PVE Manager
# 生成时间: $(Get-Date)

# 服务器配置 / Server Configuration
SERVER_HOST=$env:SERVER_HOST
SERVER_PORT=$env:SERVER_PORT

# 客户端配置 / Client Configuration  
CLIENT_HOST=$env:CLIENT_HOST
CLIENT_PORT=$env:CLIENT_PORT

# API配置 / API Configuration
API_HOST=$env:API_HOST

# WebSocket配置 / WebSocket Configuration
WS_HOST=$env:WS_HOST

# 运行环境 / Environment
NODE_ENV=$env:NODE_ENV

# CORS配置 / CORS Configuration
ALLOWED_ORIGINS=$env:ALLOWED_ORIGINS

# 数据库配置 / Database Configuration
DB_PATH=$env:DB_PATH

# 日志配置 / Logging Configuration
LOG_LEVEL=$env:LOG_LEVEL
"@
    $content | Out-File -FilePath ".env.global" -Encoding UTF8
    Print-Success "配置已保存到: .env.global"
}

# 创建前端环境配置
function Create-ClientEnv {
    $protocol = if ($env:NODE_ENV -eq "production") { "https" } else { "http" }
    $wsProtocol = if ($env:NODE_ENV -eq "production") { "wss" } else { "ws" }
    
    if (-not (Test-Path "client")) {
        Print-Error "找不到client目录，请确保在项目根目录运行此脚本"
        exit 1
    }
    
    $content = @"
# 前端环境配置 - 由start.ps1自动生成
# Frontend environment configuration - Generated by start.ps1
# 生成时间: $(Get-Date)

VITE_API_BASE_URL=${protocol}://$($env:API_HOST):$($env:SERVER_PORT)
VITE_WS_URL=${wsProtocol}://$($env:WS_HOST):$($env:SERVER_PORT)
VITE_ENV=$env:NODE_ENV
"@
    $content | Out-File -FilePath "client\.env" -Encoding UTF8
    Print-Success "前端配置已生成: client\.env"
}

# 项目初始化配置
function Init-Project {
    Print-Header "PVE Manager 项目初始化"
    
    Print-Info "开始配置项目参数..."
    Write-Host ""
    
    # 获取本机IP作为建议
    $suggestedIP = Get-LocalIP
    
    # 部署模式选择
    Write-Host "请选择部署模式:"
    Write-Host "1) 本地开发 (服务器和客户端在同一台机器)"
    Write-Host "2) 局域网部署 (服务器和客户端在不同机器)"
    Write-Host "3) 生产环境部署"
    Write-Host ""
    $deployMode = Read-Host "请选择 [1-3]"
    
    switch ($deployMode) {
        "1" {
            Print-Info "选择: 本地开发模式"
            $env:SERVER_HOST = "0.0.0.0"
            $env:CLIENT_HOST = "0.0.0.0"
            $env:API_HOST = "localhost"
            $env:WS_HOST = "localhost"
            $env:NODE_ENV = "development"
        }
        "2" {
            Print-Info "选择: 局域网部署模式"
            $env:SERVER_HOST = "0.0.0.0"
            $env:CLIENT_HOST = "0.0.0.0"
            
            if ($suggestedIP) {
                Write-Host "检测到本机IP: $suggestedIP"
                $useDetected = Read-Host "使用检测到的IP? [Y/n]"
                if ($useDetected -eq "n" -or $useDetected -eq "N") {
                    $customIP = Read-Host "请输入服务器IP地址"
                    $env:API_HOST = $customIP
                    $env:WS_HOST = $customIP
                } else {
                    $env:API_HOST = $suggestedIP
                    $env:WS_HOST = $suggestedIP
                }
            } else {
                $customIP = Read-Host "请输入服务器IP地址"
                $env:API_HOST = $customIP
                $env:WS_HOST = $customIP
            }
            $env:NODE_ENV = "development"
        }
        "3" {
            Print-Info "选择: 生产环境部署"
            $env:SERVER_HOST = "0.0.0.0"
            $env:CLIENT_HOST = "0.0.0.0"
            $prodHost = Read-Host "请输入域名或服务器地址"
            $env:API_HOST = $prodHost
            $env:WS_HOST = $prodHost
            $env:NODE_ENV = "production"
        }
        default {
            Print-Error "无效的选择"
            exit 1
        }
    }
    
    # 端口配置
    Write-Host ""
    Print-Info "配置端口 (按回车使用默认值):"
    
    $inputServerPort = Read-Host "后端服务器端口 [3000]"
    $env:SERVER_PORT = if ($inputServerPort) { $inputServerPort } else { "3000" }
    
    $inputClientPort = Read-Host "前端开发服务器端口 [5173]"
    $env:CLIENT_PORT = if ($inputClientPort) { $inputClientPort } else { "5173" }
    
    # 其他配置
    $env:ALLOWED_ORIGINS = ""
    $env:DB_PATH = "server/data"
    $env:LOG_LEVEL = "info"
    
    # 显示配置摘要
    Write-Host ""
    Print-Header "配置摘要"
    Write-ColorOutput "部署模式: $deployMode" "Cyan"
    Write-ColorOutput "API地址: http://$($env:API_HOST):$($env:SERVER_PORT)" "Cyan"
    Write-ColorOutput "WebSocket地址: ws://$($env:WS_HOST):$($env:SERVER_PORT)" "Cyan"
    Write-ColorOutput "前端地址: http://$($env:API_HOST):$($env:CLIENT_PORT)" "Cyan"
    Write-ColorOutput "运行环境: $($env:NODE_ENV)" "Cyan"
    Write-Host ""
    
    $confirm = Read-Host "确认配置并保存? [Y/n]"
    if ($confirm -eq "n" -or $confirm -eq "N") {
        Print-Info "配置已取消"
        exit 0
    }
    
    # 保存配置
    Save-Env
    Create-ClientEnv
    
    Print-Success "项目初始化完成！"
    Write-Host ""
}

# 检查环境依赖
function Check-Dependencies {
    Print-Info "检查系统依赖..."
    
    # 检查Node.js
    try {
        $nodeVersion = node --version
        Print-Info "Node.js 版本: $nodeVersion"
    } catch {
        Print-Error "Node.js 未安装，请先安装 Node.js 16+"
        exit 1
    }
    
    # 检查npm
    try {
        $npmVersion = npm --version
        Print-Info "npm 版本: $npmVersion"
    } catch {
        Print-Error "npm 未安装，请先安装 npm"
        exit 1
    }
}

# 安装项目依赖
function Install-Dependencies {
    Print-Info "检查并安装项目依赖..."
    
    # 安装根项目依赖
    if (-not (Test-Path "node_modules")) {
        Print-Info "安装根项目依赖..."
        npm install
    }
    
    # 安装服务器依赖
    if (-not (Test-Path "server\node_modules")) {
        Print-Info "安装服务器依赖..."
        Push-Location "server"
        npm install
        Pop-Location
    }
    
    # 安装客户端依赖
    if (-not (Test-Path "client\node_modules")) {
        Print-Info "安装客户端依赖..."
        Push-Location "client"
        npm install
        Pop-Location
    }
    
    Print-Success "依赖安装完成"
}

# 构建项目
function Build-Project {
    Print-Info "构建服务器代码..."
    Push-Location "server"
    try {
        npm run build
        Pop-Location
        Print-Success "构建完成"
    } catch {
        Pop-Location
        Print-Error "构建失败"
        exit 1
    }
}

# 初始化数据库
function Init-Database {
    Print-Info "检查数据库..."
    
    # 确保数据目录存在
    if (-not (Test-Path "server\data")) {
        New-Item -ItemType Directory -Path "server\data" -Force | Out-Null
    }
    
    if (-not (Test-Path "server\data\pve_manager.db")) {
        Print-Info "数据库将在首次启动时自动创建"
        Print-Info "默认管理员账户: admin / admin123"
    } else {
        Print-Success "数据库已存在"
    }
}

# 启动服务
function Start-Services {
    Print-Header "启动 PVE Manager V2.0"
    
    Print-Success "服务启动中..."
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║  PVE Manager V2.0                        ║" -ForegroundColor Cyan
    Write-Host "╠══════════════════════════════════════════╣" -ForegroundColor Cyan
    Write-Host "║  前端地址: http://$($env:API_HOST):$($env:CLIENT_PORT)" -ForegroundColor Cyan
    Write-Host "║  后端API:  http://$($env:API_HOST):$($env:SERVER_PORT)" -ForegroundColor Cyan
    Write-Host "║  运行环境: $($env:NODE_ENV)" -ForegroundColor Cyan
    Write-Host "╠══════════════════════════════════════════╣" -ForegroundColor Cyan
    Write-Host "║  默认管理员: admin / admin123            ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "主要功能:" -ForegroundColor Green
    Write-Host "  • 多用户权限管理   • 批量操作"
    Write-Host "  • 虚拟机分组       • 备份管理"
    Write-Host "  • VNC远程控制     • 定时任务"
    Write-Host "  • 操作日志审计   • 系统设置"
    Write-Host ""
    Print-Info "按 Ctrl+C 停止服务"
    Write-Host ""
    
    # 设置JWT环境变量
    if (-not $env:JWT_SECRET) {
        $env:JWT_SECRET = "pve-manager-secret-key-change-in-production"
    }
    if (-not $env:JWT_EXPIRES_IN) {
        $env:JWT_EXPIRES_IN = "24h"
    }
    
    # 启动服务
    npm run dev
}

# 显示帮助信息
function Show-Help {
    Write-Host "PVE Manager V2.0 启动脚本" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "用法:"
    Write-Host "  .\start.ps1              # 正常启动（如果未配置则进入初始化）"
    Write-Host "  .\start.ps1 -Init        # 重新初始化项目配置"
    Write-Host "  .\start.ps1 -Reset       # 重置所有配置"
    Write-Host "  .\start.ps1 -ResetDB     # 重置数据库（删除所有数据）"
    Write-Host "  .\start.ps1 -Help        # 显示帮助信息"
    Write-Host ""
    Write-Host "主要功能:" -ForegroundColor Green
    Write-Host "  • 多用户权限管理 - 支持管理员/操作员/用户/查看者角色"
    Write-Host "  • 批量操作 - 批量启动/关机/重启虚拟机"
    Write-Host "  • 虚拟机分组 - 将虚拟机分组管理"
    Write-Host "  • 备份管理 - 创建/恢复/删除备份"
    Write-Host "  • VNC远程控制 - 网页端控制台"
    Write-Host "  • 定时任务 - 定时开关机/备份"
    Write-Host "  • 操作日志 - 完整的操作审计记录"
    Write-Host "  • 系统设置 - 告警/安全/数据维护"
    Write-Host ""
    Write-Host "默认账户: admin / admin123" -ForegroundColor Yellow
    Write-Host ""
}

# 主逻辑
function Main {
    # 检查是否在项目根目录
    if (-not (Test-Path "package.json") -or -not (Test-Path "client") -or -not (Test-Path "server")) {
        Print-Error "请在PVE Manager项目根目录下运行此脚本"
        exit 1
    }
    
    if ($Help) {
        Show-Help
        exit 0
    }
    
    if ($Init) {
        Init-Project
        exit 0
    }
    
    if ($Reset) {
        Print-Warning "重置所有配置..."
        Remove-Item -Path ".env.global" -ErrorAction SilentlyContinue
        Remove-Item -Path "client\.env" -ErrorAction SilentlyContinue
        Print-Success "配置已重置"
        Init-Project
        exit 0
    }
    
    if ($ResetDB) {
        Print-Warning "重置数据库..."
        $confirm = Read-Host "确定要删除所有数据吗？此操作不可恢复! [y/N]"
        if ($confirm -eq "y" -or $confirm -eq "Y") {
            Remove-Item -Path "server\data\pve_manager.db" -ErrorAction SilentlyContinue
            Print-Success "数据库已重置，下次启动时将自动创建新数据库"
            Print-Info "默认管理员账户: admin / admin123"
        } else {
            Print-Info "操作已取消"
        }
        exit 0
    }
    
    # 正常启动流程
    Print-Header "PVE Manager V2.0 启动脚本"
    
    # 检查系统依赖
    Check-Dependencies
    
    # 加载或初始化配置
    if (-not (Load-Env)) {
        Print-Warning "未找到配置文件，开始初始化..."
        Write-Host ""
        Init-Project
        Write-Host ""
    } else {
        Print-Success "已加载配置文件"
    }
    
    # 安装依赖
    Install-Dependencies
    Write-Host ""
    
    # 构建项目
    Build-Project
    Write-Host ""
    
    # 初始化数据库
    Init-Database
    Write-Host ""
    
    # 创建前端环境配置
    Create-ClientEnv
    Write-Host ""
    
    # 启动服务
    Start-Services
}

# 运行主函数
Main
